### ISSUE TITLE
command not working 

### ISSUE THREAD

**Issue by TurtleChanYtAlt** [aroary/curiosity-issues#5]
**Describe the bug**
-robot is not working

**To Reproduce**
1. Go to '#commands'
2. do '-help'
3. Scroll down to '-robot'
4. do '-robot'
5. see error

**Expected behavior**
A robot being made from text 

**Screenshots**
none

**Additional context**
never had worked i tried it a long time ago (around like 2-5 days)

**Comment by aroary** [comment]
this command is coming soon!
it has not officially been released
